// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

export default defineConfig({
  schema: 'src/utils/prisma/schema',
  migrations: {
    path: 'src/utils/prisma/migrations',
    seed: `ts-node src/utils/prisma/${!process.env.VERCEL ? 'seed.ts' : 'seed_vercel.ts'}`,
  },

  datasource: {
    url: env('DATABASE_URL'),
  },
});
